name: Minify Uglify and Gzip

on:
  push:
    branches:
      - demo  # Replace with your branch name if different 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify the version of Node.js you need

      - name: Install dependencies
        run: npm install
        working-directory: ./path/to/your/project  # Specify the path if your package.json is not at the root

      - name: Minify and Uglify
        run: |
          # Replace with your minification and uglification command
          # Example for JavaScript files using UglifyJS
          npx uglify-js path/to/your/project/file.js -o path/to/your/project/output.min.js --compress --mangle
        working-directory: ./path/to/your/project  # If required

      - name: Gzip
        run: |
          # Gzip the minified file
          gzip path/to/your/project/output.min.js
        working-directory: ./path/to/your/project  # If required

      - name: Commit changes
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add path/to/your/project/output.min.js.gz
          git commit -m "Auto minify, uglify, and gzip"
          git push
